/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package fr.minemobs.citracloudsaves

import io.javalin.Javalin
import io.javalin.http.NotFoundResponse
import io.javalin.http.BadRequestResponse
import java.nio.file.Files
import java.nio.file.StandardOpenOption
import kotlin.io.path.Path

fun main() {
    val app = Javalin.create()
        .post("save/{gameID}") {
            val file = it.uploadedFile("save")
            if(file == null) {
                throw BadRequestResponse("Missin' the save file")
            }
            file.contentAndClose { content ->
                Files.write(Path(it.pathParam("gameID") + ".save"), content.readBytes(), StandardOpenOption.WRITE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.CREATE)
                it.result("Recieved ur file!")
            }
        }
        .get("save/{gameID}") {
            if(Files.exists(Path(it.pathParam("gameID") + ".save"))) {
                val bytes = Files.readAllBytes(Path(it.pathParam("gameID") + ".save"))
                it.result(bytes)
            } else {
                throw NotFoundResponse("Nahh mate, we couldn't find ur save")
            }
        }.start(8080)
}
